import { copyFile, mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { cases } from '../tests/pureref/adversarial-cases.mjs';

const root = new URL('../', import.meta.url);
const vault = new URL('.test-vault/', root);
const plugin = new URL('.obsidian/plugins/extended-file-support/', vault);
await mkdir(plugin, { recursive: true });
for (const name of ['main.js', 'manifest.json', 'styles.css']) {
	await copyFile(new URL(name, root), new URL(name, plugin));
}
for (const name of await readdir(new URL('tests/pureref/fixtures/', root))) {
	if (name.endsWith('.pur'))
		await copyFile(new URL(`tests/pureref/fixtures/${name}`, root), new URL(name, vault));
}
// The generated upstream demo is the primary manual test board. Keep the compact
// synthetic demo fixture under its original name for deterministic browser assertions.
await copyFile(new URL('tests/pureref/fixtures/demo.pur', root), new URL('automated-demo.pur', vault));
await copyFile(new URL('tests/pureref/fixtures/comments-demo.pur', root), new URL('demo.pur', vault));
const initial = async (path, text) => {
	try { await writeFile(new URL(path, vault), text, { flag: 'wx' }); }
	catch (error) { if (error.code !== 'EEXIST') throw error; }
};
await initial('.obsidian/community-plugins.json', '["extended-file-support"]\n');
await initial('.obsidian/app.json', '{"showUnsupportedFiles":true}\n');
await initial('.obsidian/appearance.json', '{"theme":"obsidian"}\n');
await initial('PureRef preview.md', `# PureRef plugin test vault

This isolated vault contains synthetic fixtures and the three release assets.
Enable community plugins if prompted. Test this note in Reading view and Live
Preview, and open the .pur files directly. Hover to zoom; middle-drag to pan.
Right-click for grids. The editor button opens the system application for .pur.

## Mixed board

![[demo.pur|600x400]]

## Typography

![[rich.pur]]

![[wrapped.pur]]

## Drawings

![[drawings.pur]]

## Images

![[two-images.pur]]

Text below the boards should scroll normally when the cursor is outside them.
`);
// Reading these verifies we copied real artifacts, rather than a development link.
for (const name of ['main.js', 'manifest.json', 'styles.css']) {
	console.log(`${name}: ${(await readFile(new URL(name, plugin))).byteLength} bytes`);
}
console.log(`Open this folder as an Obsidian vault: ${fileURLToPath(vault)}`);
// Dedicated generated pages can be refreshed without replacing personal notes.
const adversarial = new URL('PureRef adversarial/', vault);
await mkdir(adversarial, { recursive: true });
for (const entry of cases) {
	await writeFile(new URL(`${entry.name}.md`, adversarial), `# ${entry.title}

[[PureRef adversarial/Start here|Back to checklist]] · [[adv-${entry.name}.pur|Open file tab]]

${entry.error ? '**Expected: visible error.**' : '**Expected: supported content renders; malformed/unsupported content is omitted.**'}

${entry.check}

![[adv-${entry.name}.pur|600x400]]

## Independent second copy in a narrow viewport

![[adv-${entry.name}.pur|240x180]]

Zoom/pan one copy; the other must stay unchanged. Switch Reading view ↔ Live Preview,
resize the pane, open the file tab, and return. Scroll here outside the embed.
After an error, open [[demo.pur]] and confirm recovery.
`);
}
await writeFile(new URL('Start here.md', adversarial), `# PureRef adversarial checklist

Generated by npm run dev:pureref-vault. These pages are replaced on regeneration;
keep observations in a separate note. Reload the plugin after rebuilding.

Open each case in Reading view, Live Preview, and its file tab. Check both embed
sizes. These are synthetic adversarial files, not a native PureRef fidelity oracle.
Do not launch malformed/hostile fixtures in external applications.

${cases.map(entry => `- [ ] [[PureRef adversarial/${entry.name}|${entry.title}]]`).join('\n')}

## Manual automated checks

Run **npm run test:pureref:adversarial**, then **npm run test:pureref:report**.
The report includes each case's contract and failure screenshots for diagnosis;
there are no screenshot baselines or pixel comparisons. Neither generation nor
tests run during the build. Browser checks use an Obsidian stub; this checklist
is the real-host companion, not an automated claim about Obsidian behavior.
`);
console.log('Adversarial checklist: PureRef adversarial/Start here.md');
